version: "3.6"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/var/www
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    ports:
      - "9000:9000"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge